### ISSUE TITLE
Great project but too many package errors

### ISSUE THREAD

**Issue by LLjo** [gaborvecsei/whisper-live-transcription#5]
Nice work here, gotta say that. In case someone else have some problems you might need to install:

sudo apt install portaudio19-dev python3-pyaudio
sudo apt install nvidia-cudnn

**Comment by deforum** [comment]
this is the case with every live whisper implementation

**Comment by gaborvecsei** [comment]
@LLjo Thank you for reporting this, but this is not a problem with the solution, it's a "system dependency"
